from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field


# ----------------------------------------------------
# 1. RISK INTELLIGENCE MODELS (Adversarial Debate)
# ----------------------------------------------------
class RiskFinding(BaseModel):
    finding_id: str
    risky_clause_id: Optional[str] = None
    clause_title: str
    why_risky: str
    exposed_party: str
    consequence: str
    initial_severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CRITICAL
    evidence: str
    counter_argument: str  # Actively produced by Counterargument Agent
    counter_argument_strength: str = "MODERATE"  # WEAK, MODERATE, STRONG
    net_severity: str = "MEDIUM"
    uncertainty: float = 0.1
    suggested_mitigation: str
    requires_human_review: bool = False


class RiskReport(BaseModel):
    contract_id: str
    overall_risk_score: float = Field(default=0.0, description="0.0 (low) to 1.0 (extreme)")
    findings: List[RiskFinding] = Field(default_factory=list)
    adversarial_debate_summary: str = ""
    requires_human_escalation: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ----------------------------------------------------
# 2. NEGOTIATION INTELLIGENCE MODELS (Planner + Simulator + Critic)
# ----------------------------------------------------
class NegotiationPosition(BaseModel):
    position_id: str
    target_clause_id: Optional[str] = None
    clause_title: str
    desired_outcome: str
    acceptable_outcome: str
    fallback_position: str
    red_line: str  # Non-negotiable boundary
    concession: str  # Potential give to win this point
    leverage: str  # Commercial/legal leverage
    counter_proposal: str  # Exact proposed redline text
    simulated_counterparty_reaction: str  # Generated by Counterparty Simulator


class NegotiationStrategy(BaseModel):
    contract_id: str
    primary_objective: str
    positions: List[NegotiationPosition] = Field(default_factory=list)
    negotiation_sequence: List[str] = Field(default_factory=list)
    strategy_summary: str = ""
    critic_notes: str = ""
    requires_human_approval: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ----------------------------------------------------
# 3. COMPLIANCE INTELLIGENCE MODELS (Retrieval + Rules + Verification)
# ----------------------------------------------------
class ComplianceFinding(BaseModel):
    rule_id: str
    rule_name: str
    requirement: str
    contract_evidence: str
    compliance_status: str  # COMPLIANT, VIOLATION, AMBIGUOUS, EXEMPT
    reason: str
    confidence: float = 0.9
    source_policy: str
    recommended_action: str


class ComplianceReport(BaseModel):
    contract_id: str
    policy_name: str
    passed_rules_count: int = 0
    violations_count: int = 0
    ambiguities_count: int = 0
    findings: List[ComplianceFinding] = Field(default_factory=list)
    overall_status: str = "COMPLIANT"  # COMPLIANT, NON_COMPLIANT, REQUIRES_REVIEW
    auditor_notes: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ----------------------------------------------------
# 4. OBLIGATION INTELLIGENCE MODELS (Event-Driven Monitoring)
# ----------------------------------------------------
class ObligationItem(BaseModel):
    obligation_id: str
    party: str
    title: str
    description: str
    due_date: Optional[str] = None
    notice_days: Optional[int] = None
    type: str = "DELIVERABLE"  # PAYMENT, DELIVERABLE, RENEWAL, REPORTING, SLA
    status: str = "PENDING"  # PENDING, UPCOMING, COMPLETED, AT_RISK, BREACHED
    escalation_level: str = "NONE"  # NONE, REMINDER, WARNING, CRITICAL


class ObligationSchedule(BaseModel):
    contract_id: str
    total_obligations: int = 0
    items: List[ObligationItem] = Field(default_factory=list)
    monitoring_interval: str = "DAILY"
    active_breach_risks: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ----------------------------------------------------
# 5. DISPUTE INTELLIGENCE MODELS (Multi-Perspective Simulation + Debate)
# ----------------------------------------------------
class DisputeScenario(BaseModel):
    scenario_id: str
    clause_id: Optional[str] = None
    clause_text: str
    ambiguity_type: str  # VAGUE_STANDARD, ASYMMETRIC_OBLIGATION, MISSING_DEFINITION, CONFLICTING_TERMS
    party_a_interpretation: str  # Customer perspective
    party_b_interpretation: str  # Vendor perspective
    simulated_dispute_narrative: str
    likelihood: str = "MEDIUM"  # LOW, MEDIUM, HIGH
    severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CATASTROPHIC
    resolution_strategy: str


class DisputeAssessment(BaseModel):
    contract_id: str
    scenarios: List[DisputeScenario] = Field(default_factory=list)
    overall_dispute_risk: str = "MEDIUM"
    critic_evaluation: str = ""
    recommended_clarifications: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
